### ISSUE TITLE
Create user with extra_attributes

### ISSUE THREAD

**Issue by jenimech** [nbudin/devise_cas_authenticatable#87]
I have set `cas_create_user = true` it's work perfectly, when an user don't exist and create it. 

But I have 2 attributes on my CASserver `admin = true | false` and `name = username` I added it on my cas.yml as following:

```
          table: "users"
          username_column: "email"
          password_column: "password"
          extra_attributes:
            admin: 'admin'
            name: 'name'
```

these values are not saving on the create user proccess.

I want pass that values to the cas_client, so when the user is created have the correct value for ádmin´and ´name´. How I can do it?
Thanks.
